config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  resources :customers,only: [:show,:edit,:update]
  get '/customers/:id/leave' => "customers#leave"
  patch '/customers/:id/hide' => "customers#hide"
  resources :cart_items,only: [:index,:create,:destroy,:update]
  delete '/cart_items' => "cart_items#reset"
  get '/products/:genre_id/search' => "products#search"
  resources :products,only: [:index,:show]
  resources :shippings,only: [:new,:create,:edit,:update,:destroy]
  post '/orders/confirm' => "orders#confirm"
  get '/orders/complete' => "orders#complete"
  post '/orders/complete' => "orders#create"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders,only: [:new,:create,:index,:show]
  root to: 'home#top'
  namespace :admin do
  	get '/' => "home#top"
  	devise_for :administrators
  	resources :products,only: [:index,:new,:create,:show,:edit,:update]
  	resources :genres,only: [:index,:create,:edit,:update]
  	resources :customers,only: [:index,:show,:edit,:update]
  	resources :orders,only: [:index,:show,:update]
  	resources :order_details,only: [:update]
  end

  get 'admin/search' => "admin/search#search"
  get '/search' => "search#search"

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
	before_action :authenticate_admin_administrator!
  layout 'admin'
	def top
    @orders = Order.where(created_at: Time.zone.now.all_day)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def top
		@genres = Genre.where(is_status: true)
    @products = Product.where(is_status: true,genre_id: @genres).sample(3)
	end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/top.html.erb
<% unless customer_signed_in? %>
	<div class="row">

		<div class="col-xs-10">
			<p>ようこそ、NaganoCakeへ！<br>
				このサイトは、ケーキ販売のECサイトになります。<br>
				会員でない方も商品の閲覧はできますが、<br>
				購入には<%= link_to '会員登録',new_customer_registration_path %>が必要になります。</p>
		</div>

	</div>
<% end %>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">

      <%= render 'products/genre',genres: @genres %>

      <div class="col-xs-10">
        <h2>今週のおすすめ</h2>
        <%= render 'products/products',products: @products %>
      </div>


<div class="row store-info flex">
  <div class="store-table">
    <table class="table">
      <caption>本店基本情報</caption>
      <tbody>
        <tr>
          <th>店名</th>
          <td>NaganoCAKE 本店</td>
        </tr>
        <tr>
          <th>所在地</th>
          <td>長野県上高井郡小布施町大字小布施中町784</td>
        </tr>
        <tr>
          <th>交通手段</th>
          <td>長野電鉄　小布施駅より徒歩６分<br>小布施駅から452m</td>
        </tr>
        <tr>
          <th>TEL</th>
          <td>00-1234-5678</td>
        </tr>
        <tr>
          <th>営業時間</th>
          <td>10:00~18:00</td>
        </tr>
        <tr>
          <th>定休日</th>
          <td>水曜日、年末年始12月30日、31日、1月1日</td>
        </tr>
      </tbody>
    </table>
  </div>

  <div>
    <!-- こっからmap表示用のコード -->
    <div id="map" style="height:250px; width:400px;"></div>

    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API'] %>&callback=initMap" async ></script>

    <script>
      let map;
      function initMap() {
        geocoder = new google.maps.Geocoder()

        //マップを作成
        map = new google.maps.Map(document.getElementById('map'),{
          center: { lat: 36.696316, lng: 138.316368 },
          zoom: 15
        });

        //マーカーを立てる場所の緯度経度を指定
        marker = new google.maps.Marker({
          position: { lat: 36.696316, lng: 138.316368 },
          map: map
        });
      }
    </script>
  </div>
</div>

    </div>
  </div>